//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACE_Mall.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACE_MallEntities : DbContext
    {
        public ACE_MallEntities()
            : base("name=ACE_MallEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adm_Log> Adm_Log { get; set; }
        public virtual DbSet<Adm_User> Adm_User { get; set; }
        public virtual DbSet<Adm_User_Role> Adm_User_Role { get; set; }
        public virtual DbSet<Mall_Answer> Mall_Answer { get; set; }
        public virtual DbSet<Mall_Category> Mall_Category { get; set; }
        public virtual DbSet<Mall_Good> Mall_Good { get; set; }
        public virtual DbSet<Mall_Good_Evaluation> Mall_Good_Evaluation { get; set; }
        public virtual DbSet<Mall_Good_Specification> Mall_Good_Specification { get; set; }
        public virtual DbSet<Mall_Question> Mall_Question { get; set; }
        public virtual DbSet<My_Data> My_Data { get; set; }
        public virtual DbSet<My_Order> My_Order { get; set; }
        public virtual DbSet<My_Order_Good> My_Order_Good { get; set; }
        public virtual DbSet<My_Shopcart> My_Shopcart { get; set; }
    }
}
