//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACE_Mall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class My_Order_Good
    {
        public int ID { get; set; }
        public string OrderNo { get; set; }
        public int GoodID { get; set; }
        public Nullable<int> GoodSpecificationID { get; set; }
        public Nullable<int> GoodNumber { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int IsDelete { get; set; }
    }
}
