//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACE_Mall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Category_Good_Order
    {
        public string Name { get; set; }
        public int CategoryDelete { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int GoodID { get; set; }
        public int GoodNumber { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int OrderDelete { get; set; }
        public int GoodDelete { get; set; }
        public decimal PresentPrice { get; set; }
    }
}
