//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACE_Mall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Between
    {
        public string Name { get; set; }
        public int IsDelete { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<int> PageID { get; set; }
        public int ModuleID { get; set; }
        public string PageName { get; set; }
        public string Url { get; set; }
        public string PageIcon { get; set; }
        public string ModuleName { get; set; }
        public string ModuleIcon { get; set; }
        public int ID { get; set; }
        public int UserID { get; set; }
    }
}
